import type {
  DomainEvent,
  EventCategory,
  IssuedTicket,
  Organizer,
  TicketType,
  Venue,
} from "@/types/domain";

export const SEED_CATEGORIES: EventCategory[] = [
  {
    id: "cat-music",
    name: "Music",
    slug: "music",
    icon: "Music2",
    description: "Live music and concerts",
  },
  {
    id: "cat-wellness",
    name: "Wellness",
    slug: "wellness",
    icon: "Heart",
    description: "Health and mindfulness",
  },
  {
    id: "cat-business",
    name: "Business",
    slug: "business",
    icon: "Briefcase",
    description: "Networking and professional growth",
  },
  {
    id: "cat-arts",
    name: "Arts",
    slug: "arts",
    icon: "Palette",
    description: "Galleries, theater, and culture",
  },
  {
    id: "cat-sports",
    name: "Sports",
    slug: "sports",
    icon: "Trophy",
    description: "Games and fitness events",
  },
  {
    id: "cat-community",
    name: "Community",
    slug: "community",
    icon: "Users",
    description: "Local gatherings",
  },
];

export const SEED_VENUES: Venue[] = [
  {
    id: "ven-loft",
    name: "The Loft",
    addressLine1: "214 E 6th St",
    addressLine2: null,
    city: "Austin",
    state: "TX",
    country: "USA",
    postalCode: "78701",
    latitude: 30.2672,
    longitude: -97.7431,
    capacity: 280,
    accessibilityInfo: "Wheelchair accessible main floor.",
  },
  {
    id: "ven-park",
    name: "Riverside Park Amphitheater",
    addressLine1: "800 W Riverside Dr",
    addressLine2: null,
    city: "Denver",
    state: "CO",
    country: "USA",
    postalCode: "80211",
    latitude: 39.7392,
    longitude: -104.9903,
    capacity: 1200,
    accessibilityInfo: "Accessible viewing area near stage left.",
  },
  {
    id: "ven-hall",
    name: "Mission Hall",
    addressLine1: "450 Valencia St",
    addressLine2: null,
    city: "San Francisco",
    state: "CA",
    country: "USA",
    postalCode: "94103",
    latitude: 37.7649,
    longitude: -122.421,
    capacity: 400,
    accessibilityInfo: "Elevator to balcony.",
  },
  {
    id: "ven-chi",
    name: "Lakefront Pavilion",
    addressLine1: "337 E Randolph St",
    addressLine2: null,
    city: "Chicago",
    state: "IL",
    country: "USA",
    postalCode: "60601",
    latitude: 41.8827,
    longitude: -87.6193,
    capacity: 2000,
    accessibilityInfo: "ADA seating sections A and B.",
  },
];

export const SEED_ORGANIZERS: Organizer[] = [
  {
    id: "org-nightout",
    name: "Night Out Collective",
    handle: "nightout",
    logo: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&q=80",
    bio: "Independent promoters bringing live music to Texas.",
    verified: true,
    contactEmail: "hello@nightout.mock",
    socialLinks: { website: "https://example.com/nightout", instagram: "@nightout" },
    createdAt: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "org-flow",
    name: "Flow City Events",
    handle: "flowcity",
    logo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=200&q=80",
    bio: "Wellness experiences across the Mountain West.",
    verified: false,
    contactEmail: "team@flowcity.mock",
    socialLinks: { website: "https://example.com/flowcity" },
    createdAt: "2024-02-15T00:00:00.000Z",
  },
  {
    id: "org-summit",
    name: "Summit Labs",
    handle: "summitlabs",
    logo: null,
    bio: "Product and design workshops for builders.",
    verified: true,
    contactEmail: "events@summitlabs.mock",
    socialLinks: { twitter: "@summitlabs" },
    createdAt: "2023-11-01T00:00:00.000Z",
  },
];

function futureEnd(startIso: string, hours: number) {
  const d = new Date(startIso);
  d.setHours(d.getHours() + hours);
  return d.toISOString();
}

export function getSeedEvents(): DomainEvent[] {
  const future = (days: number, hour = 19) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    d.setHours(hour, 0, 0, 0);
    return d.toISOString();
  };

  return [
  {
    id: "evt-indie",
    slug: "indie-night-at-the-loft",
    title: "Indie Night at The Loft",
    subtitle: "Local bands and vinyl DJs",
    description:
      "Local bands, vinyl DJs, and a late-night snack bar. Doors at 7pm. All ages welcome in the cafe until 9pm.",
    shortDescription: "Live indie sets and DJ vinyl in downtown Austin.",
    category: "Music",
    categorySlug: "music",
    tags: ["live", "21+", "indie"],
    coverImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80",
    ],
    startDateTime: future(3, 19),
    endDateTime: futureEnd(future(3, 19), 4),
    timezone: "America/Chicago",
    venueId: "ven-loft",
    organizerId: "org-nightout",
    status: "published",
    featured: true,
    ageRestriction: "21+ in bar area",
    dressCode: "Casual",
    refundPolicy: "Full refund up to 48 hours before doors.",
    agenda: [
      {
        id: "ag-indie-1",
        label: "Doors",
        startTime: future(3, 19),
        endTime: futureEnd(future(3, 19), 1),
        description: "Cafe and bar open",
        speaker: null,
      },
      {
        id: "ag-indie-2",
        label: "Headliner",
        startTime: futureEnd(future(3, 19), 2),
        endTime: null,
        description: "Main stage performance",
        speaker: null,
      },
    ],
    faqItems: [
      {
        id: "faq-indie-1",
        question: "Is parking available?",
        answer: "Street parking and a paid garage one block east on 7th.",
      },
      {
        id: "faq-indie-2",
        question: "Can I bring a bag?",
        answer: "Small bags only; all bags subject to search.",
      },
    ],
    ticketTypeIds: ["tt-indie-ga", "tt-indie-vip"],
    visibility: "public",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    salesEndsAt: future(3, 18),
    ticketNote: "Mobile entry. Have your QR ready at the door.",
    presenterLine: "Night Out Collective presents",
    tagline: "Austin after dark",
    heroSubtitle: "Three bands · vinyl room · late snacks",
  },
  {
    id: "evt-yoga",
    slug: "morning-yoga-in-the-park",
    title: "Morning Yoga in the Park",
    subtitle: "All levels welcome",
    description:
      "Bring a mat and water. Guided flow for all levels, led by certified instructors. Rain date posted on our site.",
    shortDescription: "Outdoor sunrise yoga in Denver.",
    category: "Wellness",
    categorySlug: "wellness",
    tags: ["outdoor", "beginner-friendly"],
    coverImage: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&q=80",
    galleryImages: [],
    startDateTime: future(2, 8),
    endDateTime: futureEnd(future(2, 8), 1),
    timezone: "America/Denver",
    venueId: "ven-park",
    organizerId: "org-flow",
    status: "published",
    featured: true,
    ageRestriction: null,
    dressCode: "Comfortable athletic wear",
    refundPolicy: "Free cancel until 24h before start.",
    agenda: [],
    faqItems: [
      {
        id: "faq-yoga-1",
        question: "What if it rains?",
        answer: "We post a rain date within 24 hours on the event page.",
      },
    ],
    ticketTypeIds: ["tt-yoga-ga"],
    visibility: "public",
    createdAt: "2025-01-02T00:00:00.000Z",
    updatedAt: "2025-01-02T00:00:00.000Z",
    salesEndsAt: future(2, 7),
    ticketNote: "BYO mat. Arrive 15 minutes early.",
    presenterLine: "Flow City Events presents",
    tagline: "Breathe with the skyline",
    heroSubtitle: "Sunrise flow · certified guides",
  },
  {
    id: "evt-design",
    slug: "design-systems-workshop-sf",
    title: "Design Systems Workshop",
    subtitle: "Tokens to documentation",
    description:
      "Hands-on session on tokens, components, and documentation. Laptop required. Lunch included.",
    shortDescription: "Full-day workshop in San Francisco.",
    category: "Business",
    categorySlug: "business",
    tags: ["workshop", "design", "laptop-required"],
    coverImage: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80",
    ],
    startDateTime: future(10, 10),
    endDateTime: futureEnd(future(10, 10), 6),
    timezone: "America/Los_Angeles",
    venueId: "ven-hall",
    organizerId: "org-summit",
    status: "published",
    featured: true,
    ageRestriction: null,
    dressCode: null,
    refundPolicy: "50% refund until 7 days before; no refund after.",
    agenda: [
      {
        id: "ag-ds-1",
        label: "Foundations",
        startTime: future(10, 10),
        endTime: futureEnd(future(10, 10), 2),
        description: "Tokens and theming",
        speaker: "Alex Kim",
      },
      {
        id: "ag-ds-2",
        label: "Documentation lab",
        startTime: futureEnd(future(10, 10), 3),
        endTime: futureEnd(future(10, 10), 6),
        description: "Build your doc site",
        speaker: "Jordan Lee",
      },
    ],
    faqItems: [],
    ticketTypeIds: ["tt-ds-early", "tt-ds-regular"],
    visibility: "public",
    createdAt: "2025-01-03T00:00:00.000Z",
    updatedAt: "2025-01-03T00:00:00.000Z",
    salesEndsAt: future(9, 23),
    ticketNote: "Waitlist opens if early bird sells out.",
    presenterLine: "Summit Labs presents",
    tagline: "Ship consistent UI faster",
    heroSubtitle: "Hands-on · lunch included",
  },
  {
    id: "evt-jazz",
    slug: "jazz-and-wine-evening",
    title: "Jazz & Wine Evening",
    subtitle: "Intimate trio set",
    description:
      "Intimate trio set with curated wine pairings. 21+ only. Limited seating.",
    shortDescription: "Jazz trio with wine pairings in Chicago.",
    category: "Music",
    categorySlug: "music",
    tags: ["jazz", "21+", "seated"],
    coverImage: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80",
    galleryImages: [],
    startDateTime: future(5, 18),
    endDateTime: futureEnd(future(5, 18), 3),
    timezone: "America/Chicago",
    venueId: "ven-chi",
    organizerId: "org-nightout",
    status: "published",
    featured: false,
    ageRestriction: "21+",
    dressCode: "Smart casual",
    refundPolicy: "No refunds within 72 hours of showtime.",
    agenda: [],
    faqItems: [
      {
        id: "faq-jazz-1",
        question: "Dietary restrictions?",
        answer: "Email contact@nightout.mock 5 days ahead for pairings.",
      },
    ],
    ticketTypeIds: ["tt-jazz-ga"],
    visibility: "public",
    createdAt: "2025-01-04T00:00:00.000Z",
    updatedAt: "2025-01-04T00:00:00.000Z",
    salesEndsAt: future(5, 17),
    ticketNote: null,
    presenterLine: "Night Out Collective presents",
    tagline: "Sip and swing",
    heroSubtitle: "Limited seats",
  },
  {
    id: "evt-block",
    slug: "neighborhood-block-party",
    title: "Neighborhood Block Party",
    subtitle: "Food trucks and brass band",
    description:
      "Food trucks, kids zone, and live brass band. Free entry. Vendor map at the main tent.",
    shortDescription: "Family-friendly street festival in Chicago.",
    category: "Community",
    categorySlug: "community",
    tags: ["family", "outdoor", "free-tier"],
    coverImage: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&q=80",
    galleryImages: [],
    startDateTime: future(14, 17),
    endDateTime: futureEnd(future(14, 17), 4),
    timezone: "America/Chicago",
    venueId: "ven-chi",
    organizerId: "org-flow",
    status: "published",
    featured: false,
    ageRestriction: null,
    dressCode: null,
    refundPolicy: "Donation tickets are non-refundable.",
    agenda: [],
    faqItems: [],
    ticketTypeIds: ["tt-block-free", "tt-block-vip"],
    visibility: "public",
    createdAt: "2025-01-05T00:00:00.000Z",
    updatedAt: "2025-01-05T00:00:00.000Z",
    salesEndsAt: future(14, 16),
    ticketNote: "General admission is free; VIP supports the stage.",
    presenterLine: "Flow City Events presents",
    tagline: "Street eats and brass",
    heroSubtitle: "All ages · free GA",
  },
  {
    id: "evt-pitch",
    slug: "startup-pitch-open-mic-seattle",
    title: "Startup Pitch Open Mic",
    subtitle: "Three-minute pitches",
    description:
      "Three-minute pitches, friendly feedback, and networking. Sign up at the door.",
    shortDescription: "Open mic for founders in Seattle pop-up space.",
    category: "Business",
    categorySlug: "business",
    tags: ["networking", "startups"],
    coverImage: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80",
    galleryImages: [],
    startDateTime: future(7, 18),
    endDateTime: futureEnd(future(7, 18), 2),
    timezone: "America/Los_Angeles",
    venueId: "ven-hall",
    organizerId: "org-summit",
    status: "published",
    featured: false,
    ageRestriction: null,
    dressCode: "Business casual",
    refundPolicy: "Refunds until 48h before event.",
    agenda: [],
    faqItems: [],
    ticketTypeIds: ["tt-pitch-ga"],
    visibility: "public",
    createdAt: "2025-01-06T00:00:00.000Z",
    updatedAt: "2025-01-06T00:00:00.000Z",
    salesEndsAt: future(7, 17),
    ticketNote: null,
    presenterLine: "Summit Labs presents",
    tagline: "Pitch. Feedback. Connect.",
    heroSubtitle: "Open mic for builders",
  },
  {
    id: "evt-draft",
    slug: "secret-listening-party-draft",
    title: "Secret Listening Party",
    subtitle: "Draft event",
    description: "Invite-only preview. Not on public browse.",
    shortDescription: null,
    category: "Music",
    categorySlug: "music",
    tags: [],
    coverImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80",
    galleryImages: [],
    startDateTime: future(30, 20),
    endDateTime: futureEnd(future(30, 20), 2),
    timezone: "America/Chicago",
    venueId: "ven-loft",
    organizerId: "org-nightout",
    status: "draft",
    featured: false,
    ageRestriction: null,
    dressCode: null,
    refundPolicy: null,
    agenda: [],
    faqItems: [],
    ticketTypeIds: ["tt-secret-ga"],
    visibility: "unlisted",
    createdAt: "2025-01-07T00:00:00.000Z",
    updatedAt: "2025-01-07T00:00:00.000Z",
    salesEndsAt: null,
    ticketNote: null,
    presenterLine: null,
    tagline: null,
    heroSubtitle: null,
  },
  {
    id: "evt-cancelled",
    slug: "cancelled-outdoor-concert",
    title: "Outdoor Concert Series (Cancelled)",
    subtitle: "Cancelled",
    description: "This event has been cancelled. Tickets will be refunded.",
    shortDescription: null,
    category: "Music",
    categorySlug: "music",
    tags: [],
    coverImage: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80",
    galleryImages: [],
    startDateTime: future(20, 17),
    endDateTime: futureEnd(future(20, 17), 3),
    timezone: "America/Chicago",
    venueId: "ven-park",
    organizerId: "org-nightout",
    status: "cancelled",
    featured: false,
    ageRestriction: null,
    dressCode: null,
    refundPolicy: "Automatic refunds processed.",
    agenda: [],
    faqItems: [],
    ticketTypeIds: ["tt-cancel-ga"],
    visibility: "public",
    createdAt: "2025-01-08T00:00:00.000Z",
    updatedAt: "2025-01-08T00:00:00.000Z",
    salesEndsAt: null,
    ticketNote: "Cancelled",
    presenterLine: "Night Out Collective",
    tagline: null,
    heroSubtitle: null,
  },
  ];
}

export const SEED_TICKET_TYPES: TicketType[] = [
  {
    id: "tt-indie-ga",
    eventId: "evt-indie",
    name: "General Admission",
    description: "Standing room on main floor",
    price: 35,
    currency: "USD",
    inventoryTotal: 200,
    inventoryRemaining: 200,
    minPerOrder: 1,
    maxPerOrder: 6,
    saleStart: null,
    saleEnd: null,
    perks: ["Entry before 10pm"],
    status: "on_sale",
  },
  {
    id: "tt-indie-vip",
    eventId: "evt-indie",
    name: "VIP Balcony",
    description: "Balcony seating + drink voucher",
    price: 85,
    currency: "USD",
    inventoryTotal: 40,
    inventoryRemaining: 12,
    minPerOrder: 1,
    maxPerOrder: 4,
    saleStart: null,
    saleEnd: null,
    perks: ["Balcony", "1 drink voucher"],
    status: "on_sale",
  },
  {
    id: "tt-yoga-ga",
    eventId: "evt-yoga",
    name: "Suggested donation",
    description: "Pay what you can",
    price: 15,
    currency: "USD",
    inventoryTotal: 80,
    inventoryRemaining: 80,
    minPerOrder: 1,
    maxPerOrder: 4,
    saleStart: null,
    saleEnd: null,
    perks: ["Mat space"],
    status: "on_sale",
  },
  {
    id: "tt-ds-early",
    eventId: "evt-design",
    name: "Early bird",
    description: "Limited early pricing",
    price: 199,
    currency: "USD",
    inventoryTotal: 30,
    inventoryRemaining: 8,
    minPerOrder: 1,
    maxPerOrder: 2,
    saleStart: null,
    saleEnd: null,
    perks: ["Lunch included"],
    status: "on_sale",
  },
  {
    id: "tt-ds-regular",
    eventId: "evt-design",
    name: "Regular",
    description: "Standard workshop seat",
    price: 279,
    currency: "USD",
    inventoryTotal: 70,
    inventoryRemaining: 70,
    minPerOrder: 1,
    maxPerOrder: 2,
    saleStart: null,
    saleEnd: null,
    perks: ["Lunch included"],
    status: "on_sale",
  },
  {
    id: "tt-jazz-ga",
    eventId: "evt-jazz",
    name: "Seated + pairings",
    description: "Table seating with wine flight",
    price: 95,
    currency: "USD",
    inventoryTotal: 60,
    inventoryRemaining: 0,
    minPerOrder: 1,
    maxPerOrder: 2,
    saleStart: null,
    saleEnd: null,
    perks: ["Wine flight"],
    status: "sold_out",
  },
  {
    id: "tt-block-free",
    eventId: "evt-block",
    name: "General admission",
    description: "Free street festival access",
    price: 0,
    currency: "USD",
    inventoryTotal: 5000,
    inventoryRemaining: 4500,
    minPerOrder: 1,
    maxPerOrder: 10,
    saleStart: null,
    saleEnd: null,
    perks: ["Festival access"],
    status: "on_sale",
  },
  {
    id: "tt-block-vip",
    eventId: "evt-block",
    name: "VIP viewing",
    description: "Raised deck + two drink tickets",
    price: 45,
    currency: "USD",
    inventoryTotal: 100,
    inventoryRemaining: 44,
    minPerOrder: 1,
    maxPerOrder: 6,
    saleStart: null,
    saleEnd: null,
    perks: ["Deck access", "2 drink tickets"],
    status: "on_sale",
  },
  {
    id: "tt-pitch-ga",
    eventId: "evt-pitch",
    name: "Audience",
    description: "Watch pitches and network",
    price: 25,
    currency: "USD",
    inventoryTotal: 120,
    inventoryRemaining: 120,
    minPerOrder: 1,
    maxPerOrder: 5,
    saleStart: null,
    saleEnd: null,
    perks: ["Networking"],
    status: "on_sale",
  },
  {
    id: "tt-secret-ga",
    eventId: "evt-draft",
    name: "Invite",
    description: "Draft tier",
    price: 20,
    currency: "USD",
    inventoryTotal: 50,
    inventoryRemaining: 50,
    minPerOrder: 1,
    maxPerOrder: 2,
    saleStart: null,
    saleEnd: null,
    perks: [],
    status: "hidden",
  },
  {
    id: "tt-cancel-ga",
    eventId: "evt-cancelled",
    name: "GA",
    description: "Cancelled",
    price: 40,
    currency: "USD",
    inventoryTotal: 100,
    inventoryRemaining: 100,
    minPerOrder: 1,
    maxPerOrder: 4,
    saleStart: null,
    saleEnd: null,
    perks: [],
    status: "paused",
  },
];

/** Demo issued tickets for seed bookings (optional display). */
export const SEED_ISSUED_TICKETS_PLACEHOLDER: IssuedTicket[] = [];
